server:
  port: 8080  # 自定义后端服务端口

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_benefit_service?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB  # 单个文件最大大小
      max-request-size: 10MB  # 整个请求最大大小
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /images/**  # 静态资源访问路径

  web:
    resources:
      static-locations: classpath:/static/,file:${app.image.storage.path}  # 静态资源位置

# 应用配置
app:
  image:
    storage:
      path: D:/code/Java/user-benefit-service/images/  # 图片存储路径

# 图片存储和访问配置（保留，用于ImageStorageService）
image:
  storage:
    path: ./images/  # 相对路径，用于存储新上传的图片
  access:
    url: /images/   # 图片访问URL前缀

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名
      logic-delete-value: 1     # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
      id-type: auto
  mapper-locations: classpath:mapper/*.xml

# 日志配置
logging:
  level:
    com.benefit.mapper: debug  # MyBatis SQL调试日志