server:
  port: 8081  # 自定义后端服务端口

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_benefit_service?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 #逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除（0）

# 可选：日志级别配置（推荐用于开发调试 MyBatis SQL）
logging:
  level:
    com.benefit.mapper: debug

# http://localhost:8081/swagger-ui/index.html swagger主页
